"""adding_conf_num

Revision ID: ab0f52193b7e
Revises: c4ba494b1979
Create Date: 2023-08-09 06:31:25.530591

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ab0f52193b7e'
down_revision = 'c4ba494b1979'
branch_labels = None
depends_on = None


def upgrade() -> None:

    op.add_column('orders', sa.Column('conformation_number', sa.String(length=30), nullable=False), schema='ecom')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'conformation_number', schema='ecom')
