"""initDb

Revision ID: c4ba494b1979
Revises: 
Create Date: 2023-08-05 16:49:58.982433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4ba494b1979'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='ecom'
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=False),
    sa.Column('last_name', sa.String(length=20), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('phone_number', sa.Unicode(length=12), nullable=False),
    sa.Column('role', sa.Enum('Admin', 'Seller', 'User', name='role'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='ecom'
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('Placed', 'Pending', 'Shipped', 'Canceled', 'Delivered', name='orderstatus'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['ecom.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='ecom'
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('quantity_available', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['ecom.category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='ecom'
    )
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['ecom.orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['ecom.products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='ecom'
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('Approved', 'Denied', name='paymentstatus'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['ecom.orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='ecom'
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Enum('OneStar', 'TwoStar', 'ThreeStar', 'FourStar', 'FiveStar', name='rating'), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['ecom.products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['ecom.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='ecom'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name='alembic_version_pkc')
    )
    op.drop_table('reviews', schema='ecom')
    op.drop_table('payments', schema='ecom')
    op.drop_table('order_items', schema='ecom')
    op.drop_table('products', schema='ecom')
    op.drop_table('orders', schema='ecom')
    op.drop_table('users', schema='ecom')
    op.drop_table('category', schema='ecom')
    # ### end Alembic commands ###
